# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8106e6ca2c13ec11c56dc09cb3cce571d94e9284a644c8eb76ee2d70497cea5363dee6cd5c6ee7d649f49a1acb3202136bcd3f96702d80cae1f6e1d2fd69c6fd

test:
  secret_key_base: 89900b64dab1988e540e46e4a19f2947d105c16e8e0700c6639faa9243ff754402f978c8172fd6ee1ccc302027f644fcbbd0c3cfc68186241766e1936b4ad63d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["DEVISE_SECRET_KEY"] %>
